### ISSUE TITLE
Missing icon in outline

### ISSUE THREAD

**Issue by joehen** [Cooperate-Project/CooperateModelingEnvironment#114]
The outline view for the cls editor is missing an icon in oxygen:

The image could not be loaded: URLImageDescriptor(platform:/plugin/org.eclipse.team.ui/icons/full/elcl16/hierarchicalLayout.gif)

**Comment by joehen** [comment]
relates to #111

**Comment by seiferma** [comment]
You can solve this issue in the migration branch or wait for the branch to be merged into master.
