### ISSUE TITLE
MemberEnd type should be unsettable

### ISSUE THREAD

**Issue by joehen** [Cooperate-Project/CooperateModelingEnvironment#115]
The type of a member end of an association is being unset in the state calculation while it is not unsettable:
![image](https://user-images.githubusercontent.com/15814869/28248051-23c713a8-6a3d-11e7-9eec-65d12cf15a31.png)

![image](https://user-images.githubusercontent.com/15814869/28248060-498f2706-6a3d-11e7-91b4-5340c51f45d3.png)

**Comment by seiferma** [comment]
Is this still an issue?

**Comment by joehen** [comment]
Not an issue anymore
