### ISSUE TITLE
Adding comments to associations creates double entries for those in the outline view

### ISSUE THREAD

**Issue by joehen** [Cooperate-Project/CooperateModelingEnvironment#123]
![image](https://user-images.githubusercontent.com/15814869/28376976-ca86a88c-6cab-11e7-917b-b1aeb70b544b.png)

**Comment by seiferma** [comment]
I nested the comments below the commented elements and removed the duplication.

![outline](https://user-images.githubusercontent.com/9149072/28958453-b5384b5a-78f6-11e7-9cdc-52e0e4b505a7.png)
![outline2](https://user-images.githubusercontent.com/9149072/28958454-b55957d2-78f6-11e7-9231-bd5eea3c191c.png)
