### ISSUE TITLE
Graphical editor switches between diagrams after save

### ISSUE THREAD

**Issue by FPersch** [Cooperate-Project/CooperateModelingEnvironment#144]
I have two diagrams both part of the same .di in my project. When I work on one of them in the graphical editor and save my changes, the editor opens the other diagram in a new tab / switches to that tab after the save action is complete.

**Comment by seiferma** [comment]
I was unable to reproduce the issue. @joehen: Can you reproduce the issue? If not, we can close this one.

**Comment by FPersch** [comment]
Can't reproduce since issue #142 is closed.
