### ISSUE TITLE
Check compatibility of problems view filters

### ISSUE THREAD

**Issue by seiferma** [Cooperate-Project/CooperateModelingEnvironment#178]
There are filters in the problems view that might lead to unintentional hiding of problems. For instance, restricting the displayed errors to selected projects hides all issues of the textual diagram editor. We should provide a feature that checks the compatibility of settings of the problems view with the currently used editor. If settings are not compatible, we can offer to fix this to the user. We have to ensure that the message is not too disruptive or can be suppressed (maybe with a general Cooperate setting).

**Comment by FPersch** [comment]
I found no way of solving this issue in an appropriate timely manner.
