### ISSUE TITLE
Add filter for issues displayed in textual editor

### ISSUE THREAD

**Issue by seiferma** [Cooperate-Project/CooperateModelingEnvironment#180]
Users shall be able to choose the types of issues that are displayed in the textual editor. There shall be a common issue filter definition in the Cooperate preferences. The issues can be filtered by severity and maybe issue codes. For the latter, it might be necessary to define issue groups and display only these groups.

**Comment by thomcz** [comment]
filtering of markers in the problems view is no problem, but the effort of filtering issues in the textual editor is too high
