### ISSUE TITLE
Fix content navigation message

### ISSUE THREAD

**Issue by joehen** [Cooperate-Project/CooperateModelingEnvironment#2]
Avoid creating a "Cannot find navigator content extension (using triggerPoints) for object null" message when saving cooperate text editor. Is related to the appearing empty entries in the navigator and could be related to some ContentProvider for that view.

**Comment by seiferma** [comment]
Do you have some details on how to reproduce this issue? Even after applying several changes to the diagrams, I did not experience the issue.
