### ISSUE TITLE
Add full support or remove role of actors

### ISSUE THREAD

**Issue by seiferma** [Cooperate-Project/CooperateModelingEnvironment#208]
Actors in the textual diagram can be human or machine actors. This information is, however, not reflected in the graphical editor. There are two options to solve this
* Display machine actors as machines in the graphical diagram (see [discussion](https://www.eclipse.org/forums/index.php/t/831443/) in the Eclipse forums)
* Remove the role of the actors

**Comment by seiferma** [comment]
We should provide the ability to set the actor type in the graphical diagram as well.

**Comment by joehen** [comment]
Should be tested before closing

**Comment by joehen** [comment]
Tested...
