### ISSUE TITLE
Make more elements commentable

### ISSUE THREAD

**Issue by seiferma** [Cooperate-Project/CooperateModelingEnvironment#210]
Only few elements in textual class and use case diagrams are commentable. Make more elements commentable. At least, the following elements shall be supported:
* methods
* attributes
* interactions

**Comment by larissaschmid** [comment]
Papyrus does not allow to comment methods + attributes. It allows to make the following elements commentable:
* Use Case: Generalizations, Associations, Include, Extend
* Class: Packages, Generalizations, Package-Imports, Interface Realizations
* Component: Generalizations, Interface Relations
