### ISSUE TITLE
No Commit Request If Closing Eclipse

### ISSUE THREAD

**Issue by thomcz** [Cooperate-Project/CooperateModelingEnvironment#231]
If closing Eclipse without commiting changes no message appear to inform the user that he needs to commit his changes. There should be a message like if the user closes just the textual editor.

**Comment by seiferma** [comment]
You can check if there are pre-exit hooks in Eclipse that allow us to trigger custom actions. I would like to add an action that closes all Cooperate editors and thereby enforces the saving. As a positive side effect, there are no broken editors anymore after restarting Eclipse.
