### ISSUE TITLE
Check the removal and addition of optional features in class diagram

### ISSUE THREAD

**Issue by joehen** [Cooperate-Project/CooperateModelingEnvironment#232]
Check the removal and addition of optional features in the cts:

# Class Diagram

- RootPackage.rootPackage
- Class.visibility
- Class.abstract
- Class.comments
- Interface.visibility
- Interface.comments
- Attribute.visibility
- Attribute.static
- Method.visibility
- Method.abstract
- Method.static
- Method.type
- Association.role
- Association.card
- Association.twoSideBidirectionality
- Association.name
- Cardinality.upperBound

**Comment by seiferma** [comment]
Found issues:
* visibility (all elements)
* Method.type
* Association.twoSideBidirectionality
* Property.type

We treat visibility as a non optional feature because after transforming a Papyrus model to the textual models, all visibilities are set.
