### ISSUE TITLE
Add ability to export image of graphical diagram in an accessible way

### ISSUE THREAD

**Issue by seiferma** [Cooperate-Project/CooperateModelingEnvironment#246]
Exporting images of graphical diagrams is important in order to use them in documents or discuss the design with the customer. Exporting the diagram in an accessible way is essential to make them useable for documents created by blind people as well. Introduce this feature.

**Comment by FPersch** [comment]
Feature already exists, add documentation of existing papyrus feature to our wiki.
Optional create context menu entry on launcher file.

**Comment by FPersch** [comment]
Added documentation to wiki.
