### ISSUE TITLE
Deletion of elements in graphical diagrams

### ISSUE THREAD

**Issue by larissaschmid** [Cooperate-Project/CooperateModelingEnvironment#253]
After the deletion of some elements in the graphical diagram, the save fails: 

> Save Failed
com.sun.proxy.$Proxy61 cannot be cast to org.eclipse.uml2.uml.Package

It fails (with analogous error messages) for the following elements: 
* Class diagram: Package, Generalization, Implementation
* Use Case Diagram: Include, Extend
* Component Diagram: InterfaceRelations (Provide, Require) in Components, Ports 

When trying to delete a composition in a class diagram, the following exception is thrown:
> Problems occurred when invoking code from plug-in: "org.eclipse.core.databinding.observable".
    java.lang.NullPointerException
	at org.eclipse.papyrus.uml.tools.databinding.OwnerObservableValue.doGetValue(OwnerObservableValue.java:105)
	at org.eclipse.papyrus.uml.tools.databinding.OwnerObservableValue.handleChange(OwnerObservableValue.java:95)
	at org.eclipse.core.databinding.observable.ChangeEvent.dispatch(ChangeEvent.java:42)
	at org.eclipse.core.databinding.observable.ChangeManager.fireEvent(ChangeManager.java:117)
	at org.eclipse.core.databinding.observable.AbstractObservable.fireChange(AbstractObservable.java:71)
...

**Comment by seiferma** [comment]
@seiferma Investigate one element and try to find the root cause of all issues.

**Comment by seiferma** [comment]
I committed a fix. Could you investigate if the errors still appear?

**Comment by larissaschmid** [comment]
The fix works for the first exception. The second is still thrown for compositions and now for associations, too.

**Comment by seiferma** [comment]
You are right, but the exception is most probably about the known Papyrus issue [501570](https://bugs.eclipse.org/bugs/show_bug.cgi?id=501570) and does not affect the correctness of the transformation and models, right? If so, I am in favor of closing this issue as resolved.
