### ISSUE TITLE
Quickfix don't add static/final/abstract qualifier

### ISSUE THREAD

**Issue by thomcz** [Cooperate-Project/CooperateModelingEnvironment#34]
If creating a static/final/abstract method or attribute in cls editor and adding it via quickfix to uml diagram the static/final/abstract qualifier won't be added.

To reproduce:
1. add this to cls editor:
```
class Alice {
  static staticAtr : int
  final finalAtr : string
  static staticMeth() 
  final finalMeth() 
  abstract abstractMeth() 
}
```
2. add every member with quickfix into uml

**Comment by seiferma** [comment]
Another part of this issue is removing the final modifier from the meta-model and the grammar because their is no correspondence in UML.

**Comment by thomcz** [comment]
The final modifier needs to be removed from the meta-model and the grammar
