### ISSUE TITLE
Wrong ProposalProvider output if name is STRING

### ISSUE THREAD

**Issue by thomcz** [Cooperate-Project/CooperateModelingEnvironment#4]
If the name of a classifier is a STRING and the alias a ID the ProposalProvider shows the STRING but adds the alias ID into the document. The STRING name should be added into the document.

Example:
```
class "A 1" as a1
```
--> ProposalProvider shows "A 1" 
--> after clicking he adds:
```
class a1
```
--> he should add:
```
class "A 1" as a1
```

**Comment by seiferma** [comment]
The issue is caused because of ambiguities during serialization. I suggest changing the grammar as follows:
* An alias is only allowed if the name is written as a string.
* If the name is written as a string, an alias is required.
