### ISSUE TITLE
NullPointerException when deleting decorated association

### ISSUE THREAD

**Issue by FPersch** [Cooperate-Project/CooperateModelingEnvironment#49]
Steps to reproduce:

- open graphical editor
- create 2 new classes
- create new association between those 2 classes
- delete association
- NullPointerException gets thrown

**Comment by seiferma** [comment]
This is a [bug of Papyrus](https://bugs.eclipse.org/bugs/show_bug.cgi?id=501570) that has already been reported. We have to wait for them to fix the issue.
