### ISSUE TITLE
Evaluate free hosted SonarQube service

### ISSUE THREAD

**Issue by seiferma** [Cooperate-Project/CooperateModelingEnvironment#64]
SonarSource offers a hosted SonarQube instance free of charge for open source projects. Evaluate if we can use the hosted service instead of our own installation.

Reasons for switching to the hosted instance:
- Higher availability because we do not have to update the installation manually and upgrade the database afterwards
- Availability even after project ends

**Comment by joehen** [comment]
The free hosting service does not provide plugins for more exotic languages like Scala

**Comment by seiferma** [comment]
The free hosting service does not allow to configure the analysis plugins in the way we do at the moment. Using the service is, therefore, not an option.
