### ISSUE TITLE
Fix super class handling behavior in EMF switch based DerivedStateGenerators

### ISSUE THREAD

**Issue by sdkrach** [Cooperate-Project/CooperateModelingEnvironment#70]
Due to the way super classes are handled in EMF switches it is possible that a class is not handled even though the switch provides an appropriate method for it. When checking the compatibility of the switch against super types only the first super type is used. 

Currently, the effect of this limitation is a order-sensitive list of super types of each class. The super type for which the DerivedStateGenerator provides a handling operation has to be the first one in the list.

**Comment by seiferma** [comment]
We do not use the switch-based derived state generation anymore. Therefore, we will not fix this issue anymore. Though, creating enhanced versions of EMF switches that correctly handle multi-inheritance would be beneficial.
