### ISSUE TITLE
Create new Member

### ISSUE THREAD

**Issue by thomcz** [Cooperate-Project/CooperateModelingEnvironment#9]
If you create a new member (operation or property) via quickfix in the cls editor it will create the member in the uml file but does not connect it to the cls editor. It still is marked as an error and you are able to quickfix it again. After creating the member via quickfix you should not be allowed to do this and the error should vanish.

Example:
class A {
  foo() //is marked as error before and after quickfix 
}

**Comment by seiferma** [comment]
This looks like an issue in the normalizers of the scoping. An FQN is created instead of a simple name.

**Comment by seiferma** [comment]
Could you check if the issue still exists? After my last commit, I could not reproduce it anymore.
