### ISSUE TITLE
Provide ability to reset repository to previous state

### ISSUE THREAD

**Issue by seiferma** [Cooperate-Project/CooperateModelingEnvironment#94]
Even if we work on branches and merge back into master after successful model transformations, we cannot always guarantee that the state in the master repository is valid. Therefore, we should provide a feature that allows resetting the whole repository (or single diagrams) to a previous state.

You can use the CDO history features to recreate the old state by readding the old models. There might be more sophisticated features in the CDO api, which should be checked.

**Comment by FPersch** [comment]
While working on this issue I came across a forum entry [1] and an enhancement request for CDO [2] which are similar to this issue.
[1] [[CDO] CDO version/history/revision functionality](https://www.eclipse.org/forums/index.php/t/450110/)
[2] [Bug 260036 - Provide "revert to the history revision" operation ](https://bugs.eclipse.org/bugs/show_bug.cgi?id=260036)
